### Importing warnings to avoid any Warnings

In [1]:
import warnings
warnings.filterwarnings('ignore')

### Importing Pandas and Numpy

In [2]:
import pandas as pd
import numpy as np

### Loading CSV File

In [3]:
data=pd.read_csv('KS.csv')

### Size of our Dataset


In [4]:
print(data.shape)

(316, 7)


### Lets Know our Parameters

In [5]:
data.columns

Index(['gravity', 'ph', 'osmo', 'cond', 'urea', 'calc', 'target'], dtype='object')

### Lets See is there any Null Values

In [6]:
data.isnull().sum()

gravity    0
ph         0
osmo       0
cond       0
urea       0
calc       0
target     0
dtype: int64

In [7]:
# So There were no null values

### Lets Check Unique Values


In [8]:
data['gravity'].unique()

array([1.021, 1.017, 1.008, 1.011, 1.005, 1.02 , 1.012, 1.029, 1.015,
       1.025, 1.006, 1.007, 1.018, 1.014, 1.024, 1.019, 1.023, 1.01 ,
       1.009, 1.026, 1.013, 1.022, 1.031, 1.04 , 1.034, 1.033, 1.028,
       1.027, 1.016])

In [9]:
data['ph'].unique()

array([4.91, 5.74, 7.2 , 5.51, 6.52, 5.27, 5.62, 5.67, 5.41, 6.13, 6.19,
       5.53, 7.12, 5.35, 5.21, 4.9 , 6.63, 6.81, 6.88, 6.14, 6.3 , 5.47,
       7.38, 5.96, 5.68, 6.76, 7.61, 6.61, 5.87, 5.44, 7.92, 5.98, 6.56,
       5.94, 5.85, 5.66, 6.4 , 6.35, 6.37, 6.18, 5.33, 5.64, 6.79, 5.97,
       5.77, 5.6 , 5.36, 5.16, 5.86, 6.27, 7.01, 6.21, 5.73, 7.94, 6.28,
       5.56, 5.71, 5.24, 5.58, 5.9 , 6.75, 6.9 , 6.29, 4.76, 5.4 , 5.14,
       5.09, 7.9 , 4.81, 6.03])

In [10]:
data['osmo'].unique()

array([ 725,  577,  321,  408,  187,  668,  461, 1107,  543,  779,  345,
        907,  242,  283,  450,  684,  253,  947,  395,  565,  874,  760,
        631,  749,  455,  527,  225,  241,  781,  680,  579,  559,  256,
        970,  702,  341,  704,  325,  694,  815,  386,  541,  343,  876,
        774,  698,  866,  775,  853,  822,  531,  371,  443,  442,  364,
        567,  838,  658,  854,  956, 1236, 1032,  487,  516,  456,  251,
        945,  833,  312,  840,  703,  736,  721,  410,  803,  594,  416],
      dtype=int64)

In [11]:
data['cond'].unique()

array([14. , 20. , 14.9, 12.6,  7.5, 25.3, 17.4, 35.9, 21.9, 25.7, 11.5,
       28.4, 11.3,  9.9, 17.9, 26.1,  8.4, 32.6, 23.6, 29.9, 33.8, 30.1,
       11.2, 29. ,  8.8, 25.8,  9.8,  5.1, 15.5, 15.8,  8.1, 38. , 14.6,
       24.5, 12.2, 23.3, 26. , 17.7, 20.9, 13.4, 35.8, 27.9, 19.5, 29.5,
       31.2, 27.6, 21.4, 20.6, 10.9, 19.7, 14.3, 27. , 27.3, 29.1, 14.8,
       20.8, 17.8, 33.6, 22.2, 12.4, 19.8, 13.3, 21.8, 12.8])

In [12]:
data['urea'].unique()

array([443, 296, 101, 224,  91, 252, 195, 550, 170, 382, 152, 448,  64,
       147, 161, 284, 133, 395,  95, 214, 380, 199,  87, 422, 239, 270,
        75,  72, 159, 349, 282, 297, 317, 130, 362, 330, 125, 260,  97,
       311, 385, 104, 187, 126, 308, 325, 354, 360, 302, 364, 301, 197,
       188, 124, 398, 516, 212, 486, 473, 620, 430, 198, 184, 164, 141,
       396, 457,  10, 272, 418, 394, 255, 178], dtype=int64)

In [13]:
data['calc'].unique()

array([ 2.45,  4.49,  2.36,  2.15,  1.16,  3.34,  1.4 ,  8.48,  2.21,
        1.93,  1.27,  1.03,  1.47,  1.53,  5.09,  1.05,  2.03,  7.68,
        1.45,  5.16,  0.81,  1.32,  1.55,  1.52,  0.77,  2.17,  0.17,
        0.83,  3.04,  1.06,  3.93,  5.38,  3.53,  4.54,  3.98,  1.02,
        3.46,  1.19,  5.64,  2.66,  1.22,  2.64,  2.31,  6.96, 13.  ,
        5.54,  6.19,  7.31, 14.34,  4.74,  2.5 ,  4.18,  3.1 ,  3.01,
        6.81,  8.28,  2.33,  7.18,  5.67, 12.68,  8.94,  3.16,  3.3 ,
        6.99,  0.65,  4.45,  0.27,  7.64,  6.63,  8.53,  9.04,  0.58,
        7.82, 12.2 ,  9.39])

In [14]:
data['target'].unique()

array([0, 1], dtype=int64)

### Let we see first five rows of the data

In [15]:
data.head()

gravity    ph  osmo  cond  urea  calc  target
0    1.021  4.91   725  14.0   443  2.45       0
1    1.017  5.74   577  20.0   296  4.49       0
2    1.008  7.20   321  14.9   101  2.36       0
3    1.011  5.51   408  12.6   224  2.15       0
4    1.005  6.52   187   7.5    91  1.16       0

### Let's locate our central Values in Each Column

In [16]:
data.describe()

gravity          ph         osmo        cond        urea  \
count  316.000000  316.000000   316.000000  316.000000  316.000000   
mean     1.018114    6.028481   612.848101   20.813924  266.405063   
std      0.007205    0.720850   236.381026    7.901099  130.628033   
min      1.005000    4.760000   187.000000    5.100000   10.000000   
25%      1.012000    5.530000   410.000000   14.000000  159.000000   
50%      1.018000    5.940000   594.000000   21.400000  260.000000   
75%      1.024000    6.400000   803.000000   27.000000  380.000000   
max      1.040000    7.940000  1236.000000   38.000000  620.000000   

             calc      target  
count  316.000000  316.000000  
mean     4.138987    0.430380  
std      3.244490    0.495915  
min      0.170000    0.000000  
25%      1.450000    0.000000  
50%      3.160000    0.000000  
75%      6.190000    1.000000  
max     14.340000    1.000000

In [17]:
data['target'].value_counts()

0    180
1    136
Name: target, dtype: int64

In [18]:
data.corr()

gravity        ph      osmo      cond      urea      calc    target
gravity  1.000000 -0.253340  0.861466  0.559064  0.823477  0.525699  0.419818
ph      -0.253340  1.000000 -0.238841 -0.097680 -0.275557 -0.119488 -0.112191
osmo     0.861466 -0.238841  1.000000  0.812780  0.871178  0.522979  0.231834
cond     0.559064 -0.097680  0.812780  1.000000  0.495405  0.351030  0.059717
urea     0.823477 -0.275557  0.871178  0.495405  1.000000  0.502327  0.258402
calc     0.525699 -0.119488  0.522979  0.351030  0.502327  1.000000  0.537728
target   0.419818 -0.112191  0.231834  0.059717  0.258402  0.537728  1.000000